services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
  app:
    container_name: fitu-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    env_file:
      - ./.env

volumes:
  mysql_data: